import Foundation
import AppKit
import Combine
import UniformTypeIdentifiers
import CryptoKit

/// Clipboard coordinator. Captured text, paths, and script input are never logged.
class ClipboardManager: ObservableObject {
    static let shared = ClipboardManager()
    @Published var clipboardItems: [ClipboardItem] = []
    @Published var unreadCount = 0
    @Published var searchText = "" { didSet { updateFilteredItems() } }
    @Published var filteredItems: [ClipboardItem] = []
    @Published var lastError: String? { didSet { lastErrorProvider = nil } }
    private var lastErrorProvider: (() -> String)?
    private var languageObserver: NSObjectProtocol?
    @Published var isMonitoring = false
    @Published var canUndo = false
    private var timer: Timer?
    private let monitoringPasteboard: NSPasteboard
    private let settings: SettingsManager
    private var lastChangeCount: Int
    /// Each entry contains only removed records. Undo must retain records captured afterward.
    private var undoItems: [[ClipboardItem]] = []
    private var lastCapturedFingerprint: String?
    private var lastCapturedID: UUID?
    private var loadedDataVersion: Int?
    private var temporaryPasteDirectories: [URL] = []
    private var temporaryImageDragDirectory: URL?
    private static let memoryArchiveType = "local.cclip.memory-attachments-v1"
    var onCapture: ((ClipboardItem) -> Void)?
    var textTransform: ((String, String) throws -> String)?
    var captureAllowed: () -> Bool = { true }
    var excludedApplications: Set<String> = []
    var sensitivePatterns: [String] = []
    internal lazy var store = ClipboardStore(getCleanupDays: { [weak self] in
        guard let self, self.settings.enableHistoryPersistence else { return 0 }
        return self.settings.autoCleanupDays
    })

    init(store: ClipboardStore? = nil, board: NSPasteboard = .general, settings: SettingsManager = .shared) {
        self.monitoringPasteboard = board
        self.lastChangeCount = board.changeCount
        self.settings = settings
        if let store { self.store = store }
        reload()
        languageObserver = NotificationCenter.default.addObserver(forName: AppLanguage.didChange, object: nil, queue: .main) { [weak self] _ in
            guard let self else { return }
            if let provider = self.lastErrorProvider { self.setError(provider) }
        }
    }

    private func setError(_ provider: (() -> String)?) {
        lastError = provider?()
        lastErrorProvider = provider
    }

    private func setError(_ error: Error) {
        setError { error.localizedDescription }
    }

    func startMonitoring() {
        guard timer == nil else { return }
        lastChangeCount = monitoringPasteboard.changeCount
        isMonitoring = true
        timer = Timer.scheduledTimer(withTimeInterval: max(0.2, settings.monitoringInterval), repeats: true) { [weak self] _ in self?.poll() }
    }
    func stopMonitoring() { timer?.invalidate(); timer = nil; isMonitoring = false }
    func updateUserActivity() {}
    func clearUnreadCount() { unreadCount = 0 }
    func markAsRead() { clearUnreadCount() }

    private func poll() {
        guard monitoringPasteboard.changeCount != lastChangeCount else { return }
        let application = NSWorkspace.shared.frontmostApplication
        poll(sourceApp: application?.bundleIdentifier, sourceAppName: application?.localizedName)
    }

    /// Share the change-count boundary with named-pasteboard tests without reading the desktop.
    func poll(sourceApp: String?, sourceAppName: String? = nil) {
        guard monitoringPasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = monitoringPasteboard.changeCount
        do { _ = try capture(from: monitoringPasteboard, sourceApp: sourceApp, sourceAppName: sourceAppName) }
        catch { setError(error) }
    }

    /// The same capture/filter path serves monitoring and isolated named-pasteboard tests.
    @discardableResult
    func capture(from board: NSPasteboard, sourceApp: String?, sourceAppName: String? = nil) throws -> ClipboardItem? {
        guard captureAllowed(), !excludedApplications.contains(sourceApp ?? "") else { return nil }
        let privateTypes: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        guard !(board.types ?? []).contains(where: { privateTypes.contains($0.rawValue) }) else { return nil }
        guard var item = try Self.readItem(from: board) else { return nil }
        item.sourceApp = sourceApp
        item.sourceAppName = Self.nonempty(sourceAppName) ?? Self.resolveSourceAppName(for: sourceApp)
        var transformFailure: (() -> String)?
        if item.type == .text {
            guard !sensitivePatterns.contains(where: { !$0.isEmpty && item.content.range(of: $0, options: .regularExpression) != nil }) else { return nil }
            if let textTransform {
                do {
                    let output = try textTransform(item.content, "copy")
                    if output != item.content { item.content = output; item.representations = nil; item.data = nil }
                } catch { transformFailure = { AppLanguage.text("自动脚本失败，已保留原文：", "Automatic script failed; the original content was kept: ") + error.localizedDescription } }
            }
        }
        let fingerprint = captureFingerprint(item)
        if lastCapturedFingerprint == fingerprint, let id = lastCapturedID, clipboardItems.contains(where: { $0.id == id }) { return nil }
        if let recent = clipboardItems.max(by: { $0.timestamp < $1.timestamp }), captureFingerprint(recent) == fingerprint { return nil }
        let saved = try ingest(item)
        lastCapturedFingerprint = fingerprint; lastCapturedID = saved.id
        unreadCount += 1
        onCapture?(saved) // Workflows receive owned attachment paths, never stale source paths.
        if let transformFailure { setError(transformFailure) }
        return saved
    }

    /// Resolve only a known application identifier; clipboard text is never used to infer provenance.
    static func resolveSourceAppName(for identifier: String?) -> String? {
        guard let identifier = nonempty(identifier),
              let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: identifier),
              let bundle = Bundle(url: url) else { return nil }
        return nonempty(bundle.object(forInfoDictionaryKey: "CFBundleDisplayName") as? String)
            ?? nonempty(bundle.object(forInfoDictionaryKey: "CFBundleName") as? String)
            ?? nonempty(url.deletingPathExtension().lastPathComponent)
    }

    private static func nonempty(_ value: String?) -> String? {
        guard let value = value?.trimmingCharacters(in: .whitespacesAndNewlines), !value.isEmpty else { return nil }
        return value
    }

    private func captureFingerprint(_ item: ClipboardItem) -> String {
        // A new application is a new copy event even when its bytes match the previous clip.
        // Prefer the stable identifier so an application's localized name does not defeat deduplication.
        let source = Self.nonempty(item.sourceApp).map { "bundle:" + $0 }
            ?? Self.nonempty(item.sourceAppName).map { "name:" + $0 } ?? "unknown"
        return createItemHash(item) + "|" + source
    }

    static func readItem(from board: NSPasteboard) throws -> ClipboardItem? {
        let files = (board.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL] ?? []).filter(\.isFileURL)
        if !files.isEmpty {
            // A chat application publishes an image copy as both its own cache path and real image bytes,
            // while a file copy carries no image format at all. Only the former is an image content copy.
            if files.count == 1, fileType(files[0]) == .image, let data = imageData(from: board, file: files[0]) {
                var item = ClipboardItem(id: UUID(), content: "Image", type: .image, timestamp: Date(), data: data)
                item.representations = try imageRepresentations(from: board)
                return item
            }
            var item = ClipboardItem(id: UUID(), content: files.map(\.lastPathComponent).joined(separator: "\n"), type: fileType(files[0]), timestamp: Date(), filePath: files.first?.path)
            item.fileURLs = files.map(\.path)
            return item
        }
        var representations: [String: Data] = [:]
        var size = 0
        for type in board.types ?? [] {
            // AppKit also exposes legacy display names such as "Apple HTML pasteboard type";
            // modern NSPasteboardItem writers require actual UTI identifiers.
            guard Self.isWritableRepresentation(type.rawValue) else { continue }
            guard let data = board.data(forType: type) else { continue }
            size += data.count
            guard size <= 64 * 1024 * 1024 else { throw ClipboardError.dataCorrupted }
            representations[type.rawValue] = data
        }
        let text = board.string(forType: .string)
            ?? board.data(forType: .rtf).flatMap { NSAttributedString(rtf: $0, documentAttributes: nil)?.string }
        if let text, !text.isEmpty {
            var item = ClipboardItem(id: UUID(), content: text, type: .text, timestamp: Date())
            item.representations = representations
            return item
        }
        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            if let data = board.data(forType: type), NSImage(data: data) != nil {
                var item = ClipboardItem(id: UUID(), content: "Image", type: .image, timestamp: Date(), data: data)
                item.representations = representations
                return item
            }
        }
        return nil
    }
    private static func isWritableRepresentation(_ type: String) -> Bool {
        type.contains(".") && type.unicodeScalars.allSatisfy { CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-").contains($0) }
    }
    /// Image formats on the pasteboard are what marks an image-content copy; a plain file copy carries none.
    /// The source file is preferred for storage so JPEG or HEIC encoding survives, with the pasteboard as fallback.
    private static func imageData(from board: NSPasteboard, file: URL) -> Data? {
        var fromBoard: Data?
        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            if let bytes = board.data(forType: type), NSImage(data: bytes) != nil { fromBoard = bytes; break }
        }
        guard let format = fromBoard else { return nil }
        if let size = try? file.resourceValues(forKeys: [.fileSizeKey]).fileSize, size <= 64 * 1024 * 1024,
           let bytes = try? Data(contentsOf: file), NSImage(data: bytes) != nil { return bytes }
        return format
    }
    /// An image item keeps image formats only: the same pasteboard's file-url and filename list point into
    /// the source application's own cache, and writing them back would hand receivers a path they cannot read.
    private static func imageRepresentations(from board: NSPasteboard) throws -> [String: Data] {
        var result: [String: Data] = [:]
        var size = 0
        for type in board.types ?? [] {
            guard isWritableRepresentation(type.rawValue), UTType(type.rawValue)?.conforms(to: .image) == true else { continue }
            guard let data = board.data(forType: type) else { continue }
            size += data.count
            guard size <= 64 * 1024 * 1024 else { throw ClipboardError.dataCorrupted }
            result[type.rawValue] = data
        }
        return result
    }
    static func fileType(_ url: URL) -> ClipboardItemType {
        guard let type = UTType(filenameExtension: url.pathExtension) else { return .file }
        if type.conforms(to: .image) { return .image }
        if type.conforms(to: .movie) { return .video }
        if type.conforms(to: .audio) { return .audio }
        if type.conforms(to: .archive) { return .archive }
        if type.conforms(to: .sourceCode) { return .code }
        if type.conforms(to: .application) { return .executable }
        if type.conforms(to: .text) || type.conforms(to: .pdf) { return .document }
        return .file
    }

    @discardableResult func ingest(_ item: ClipboardItem) throws -> ClipboardItem {
        guard captureAllowed() else { throw ClipboardError.accessDenied }
        let saved: ClipboardItem
        if settings.enableHistoryPersistence {
            if let previous = loadedDataVersion, previous != (try store.dataVersion()) {
                clipboardItems = try store.readItems()
            }
            saved = try store.upsert(item)
            try store.setItemLimit(settings.maxItems)
            let ids = try store.itemIDs()
            var updated = clipboardItems.filter { ids.contains($0.id) && $0.id != saved.id }
            let known = Set(updated.map(\.id)).union([saved.id])
            for id in ids.subtracting(known) { if let item = try store.readItem(id: id) { updated.append(item) } }
            if ids.contains(saved.id) { updated.insert(saved, at: 0) }
            clipboardItems = updated
            loadedDataVersion = try store.dataVersion()
        } else {
            saved = try memorySnapshot(item)
            var updated = clipboardItems.filter { $0.id != saved.id }
            updated.insert(saved, at: 0)
            let retained = limited(updated)
            let bytes = (retained + undoItems.flatMap { $0 }).reduce(0) { $0 + $1.residentPayloadBytes }
            guard bytes <= 256 * 1024 * 1024 else {
                throw ClipboardStorageError.unsupportedAttachment("仅内存历史已达 256 MiB，未记录本次内容；可释放历史或开启持久保存。", "Memory-only history reached 256 MiB. This capture was not saved; free history or enable persistence.")
            }
            clipboardItems = retained
        }
        lastError = nil
        changed()
        return saved
    }
    @discardableResult func addText(_ text: String) throws -> ClipboardItem {
        try ingest(ClipboardItem(id: UUID(), content: text, type: .text, timestamp: Date()))
    }
    @discardableResult func addImage(_ data: Data) throws -> ClipboardItem {
        guard NSImage(data: data) != nil else { throw ClipboardError.dataCorrupted }
        return try ingest(ClipboardItem(id: UUID(), content: "Image", type: .image, timestamp: Date(), data: data))
    }

    /// Copy once through the monitored writer, then report history persistence separately.
    /// A successful copy must not be recaptured under whichever app regains focus afterward.
    @discardableResult func copyScreenshot(_ data: Data) throws -> Result<ClipboardItem, Error> {
        guard captureAllowed() else { throw ClipboardError.accessDenied }
        guard NSImage(data: data) != nil else { throw ClipboardError.dataCorrupted }
        let item = ClipboardItem(id: UUID(), content: "Image", type: .image, timestamp: Date(), data: data,
                                 sourceApp: Bundle.main.bundleIdentifier ?? "local.cclip.app", sourceAppName: "Xclip")
        try writeToClipboard(item)
        return Result { try ingest(item) }
    }
    func reload() {
        guard settings.enableHistoryPersistence else { changed(); return }
        do { clipboardItems = try store.readItems(); loadedDataVersion = try store.dataVersion(); lastError = nil; changed() }
        catch { setError(error) } // Keep the last usable in-memory snapshot.
    }
    /// Called after a validated explicit backup import. Session-only mode remains session-only.
    func adoptImportedHistory(_ items: [ClipboardItem], merge: Bool = true) throws {
        if settings.enableHistoryPersistence { clipboardItems = items }
        else {
            let snapshots = try items.map(memorySnapshot)
            let incoming = Set(snapshots.map(\.id))
            clipboardItems = (merge ? clipboardItems.filter { !incoming.contains($0.id) } : []) + snapshots
        }
        lastError = nil
        changed()
    }

    func changed() {
        clipboardItems.sort { $0.isPinned == $1.isPinned ? $0.timestamp > $1.timestamp : $0.isPinned }
        updateFilteredItems()
        NotificationCenter.default.post(name: NSNotification.Name("ClipboardItemsChanged"), object: nil)
    }
    func update(_ item: ClipboardItem) {
        var updated = item
        if let previous = clipboardItems.first(where: { $0.id == item.id }), previous.content != item.content,
           item.type == .text || (item.type == .code && item.filePath == nil && (item.fileURLs ?? []).isEmpty) {
            updated.data = nil; updated.representations = nil
        }
        do { _ = try ingest(updated) } catch { setError(error) }
    }
    func copyToClipboard(item: ClipboardItem) { do { try writeToClipboard(item) } catch { setError(error) } }
    func restoreToClipboard(_ item: ClipboardItem) { copyToClipboard(item: item) }

    /// Keep file/image batches as distinct pasteboard objects. Text-only batches join by the chosen separator.
    func writeItemsToClipboard(_ items: [ClipboardItem], separator: String = "\n", board requestedBoard: NSPasteboard? = nil) throws {
        guard captureAllowed(), !items.isEmpty else { throw ClipboardError.accessDenied }
        let destination = requestedBoard ?? monitoringPasteboard
        if items.count == 1 { try writeToClipboard(items[0], board: destination); return }
        let items = try items.map { try $0.materialized() }
        if items.allSatisfy({ $0.type == .text || ($0.type == .code && $0.filePath == nil && ($0.fileURLs ?? []).isEmpty) }) {
            try writeToClipboard(ClipboardItem(id: UUID(), content: items.map(\.content).joined(separator: separator), type: .text, timestamp: Date()), board: destination)
            return
        }
        let staging = NSPasteboard(name: .init("CClip.Batch.\(UUID().uuidString)"))
        defer { staging.releaseGlobally() }
        var writers: [NSPasteboardItem] = []
        var warnings: [() -> String] = []
        for item in items {
            try writeToClipboard(item, board: staging)
            if let provider = lastErrorProvider { warnings.append(provider) }
            else if let lastError { warnings.append { lastError } }
            for representation in staging.pasteboardItems ?? [] {
                let writer = NSPasteboardItem()
                for type in representation.types where Self.isWritableRepresentation(type.rawValue) {
                    if let bytes = representation.data(forType: type) {
                        guard writer.setData(bytes, forType: type) else { throw ClipboardError.dataCorrupted }
                    }
                }
                guard !writer.types.isEmpty else { throw ClipboardError.dataCorrupted }
                writers.append(writer)
            }
        }
        guard !writers.isEmpty, captureAllowed() else { throw ClipboardError.accessDenied }
        destination.clearContents()
        guard destination.writeObjects(writers) else { throw ClipboardError.accessDenied }
        if destination.name == monitoringPasteboard.name { lastChangeCount = destination.changeCount }
        setError(warnings.isEmpty ? nil : { warnings.map { $0() }.joined(separator: "\n") })
    }

    func writeToClipboard(_ item: ClipboardItem, plainText: Bool = false, board requestedBoard: NSPasteboard? = nil) throws {
        guard captureAllowed() else { throw ClipboardError.accessDenied }
        let board = requestedBoard ?? monitoringPasteboard
        let item = try item.materialized() // Validate before clearing or mutating any pasteboard.
        if let bytes = item.representations?[Self.memoryArchiveType] {
            let archive = try JSONDecoder().decode(HistoryArchive.self, from: bytes)
            let directory = SessionTemporaryFiles.root.appendingPathComponent("cclip-paste-\(UUID().uuidString)")
            do {
                try FileManager.default.createDirectory(at: SessionTemporaryFiles.root, withIntermediateDirectories: true)
                guard let materialized = try archive.unpack(to: directory).first else { throw ClipboardError.dataCorrupted }
                try SessionTemporaryFiles.mark(directory)
                try writeToClipboard(materialized, plainText: plainText, board: board)
                temporaryPasteDirectories.append(directory)
                return
            } catch { try? FileManager.default.removeItem(at: directory); throw error }
        }
        var scriptFailure: (() -> String)?
        if item.type == .text || (item.type == .code && item.filePath == nil && (item.fileURLs ?? []).isEmpty) {
            var text = item.content
            do { text = try textTransform?(item.content, "paste") ?? item.content }
            catch { scriptFailure = { AppLanguage.text("自动脚本失败，已粘贴原文：", "Automatic script failed; the original content was pasted: ") + error.localizedDescription } }
            let writer = NSPasteboardItem()
            if !plainText, text == item.content, let representations = item.representations {
                for (type, data) in representations where Self.isWritableRepresentation(type) { guard writer.setData(data, forType: .init(type)) else { throw ClipboardError.dataCorrupted } }
            }
            guard writer.setString(text, forType: .string) else { throw ClipboardError.dataCorrupted }
            board.clearContents()
            guard board.writeObjects([writer]) else { throw ClipboardError.accessDenied }
        } else if let paths = item.fileURLs, !paths.isEmpty {
            let urls = paths.map { URL(fileURLWithPath: $0) }
            guard urls.allSatisfy({ FileManager.default.fileExists(atPath: $0.path) }) else { throw ClipboardError.dataCorrupted }
            board.clearContents()
            guard board.writeObjects(urls as [NSURL]) else { throw ClipboardError.accessDenied }
        } else if item.type == .image {
            guard let data = item.data ?? item.filePath.flatMap({ try? Data(contentsOf: URL(fileURLWithPath: $0)) }),
                  let image = NSImage(data: data) else { throw ClipboardError.dataCorrupted }
            let writer = NSPasteboardItem()
            if let representations = item.representations, !plainText {
                for (type, bytes) in representations where Self.isWritableRepresentation(type) { guard writer.setData(bytes, forType: .init(type)) else { throw ClipboardError.dataCorrupted } }
            }
            if data.starts(with: [137, 80, 78, 71, 13, 10, 26, 10]) { writer.setData(data, forType: .png) }
            else if writer.data(forType: .tiff) == nil, let tiff = image.tiffRepresentation { writer.setData(tiff, forType: .tiff) }
            board.clearContents()
            guard board.writeObjects([writer]) else { throw ClipboardError.accessDenied }
        } else if let path = item.filePath, FileManager.default.fileExists(atPath: path) {
            board.clearContents()
            guard board.writeObjects([URL(fileURLWithPath: path) as NSURL]) else { throw ClipboardError.accessDenied }
        } else { throw ClipboardError.dataCorrupted }
        if board.name == monitoringPasteboard.name { lastChangeCount = board.changeCount }
        setError(scriptFailure)
    }

    /// A drag destination may read the URL after the panel closes. Keep exported
    /// images for this app session, just like materialized memory-only attachments.
    func imageDragFile(for png: Data) throws -> URL {
        if temporaryImageDragDirectory == nil {
            let directory = try SessionTemporaryFiles.create(prefix: "cclip-image-drag-")
            temporaryPasteDirectories.append(directory)
            temporaryImageDragDirectory = directory
        }
        guard let directory = temporaryImageDragDirectory else { throw ClipboardError.dataCorrupted }
        let digest = SHA256.hash(data: png).map { String(format: "%02x", $0) }.joined()
        let imageDirectory = directory.appendingPathComponent(digest, isDirectory: true)
        try FileManager.default.createDirectory(at: imageDirectory, withIntermediateDirectories: true)
        // Attachment receivers can deduplicate by the visible filename even
        // when the parent directories differ. Give each image its own stable
        // name, while repeated drags of the same pixels reuse the same export.
        let url = imageDirectory.appendingPathComponent("Xclip-\(digest.prefix(24)).png")
        if !FileManager.default.fileExists(atPath: url.path) {
            try png.write(to: url, options: .atomic)
        }
        return url
    }

    func cleanupImageDragFiles() {
        guard let directory = temporaryImageDragDirectory else { return }
        try? FileManager.default.removeItem(at: directory)
        temporaryPasteDirectories.removeAll { $0 == directory }
        temporaryImageDragDirectory = nil
    }

    private func recordDeletion(_ items: [ClipboardItem]) {
        guard !items.isEmpty else { return }
        undoItems.append(items)
        if undoItems.count > 20 { undoItems.removeFirst() }
        canUndo = true
    }
    func deleteItem(_ item: ClipboardItem) { deleteItems(where: { $0.id == item.id }) }
    func deleteItems(_ items: [ClipboardItem]) {
        let ids = Set(items.map(\.id))
        deleteItems(where: { ids.contains($0.id) })
    }
    func clearAllItems() { deleteItems(where: { !$0.isFavorite && !$0.isPinned }) }
    private func deleteItems(where predicate: (ClipboardItem) -> Bool) {
        let removed = clipboardItems.filter(predicate)
        guard !removed.isEmpty else { return }
        do {
            if settings.enableHistoryPersistence {
                try store.deleteItems(ids: removed.map(\.id))
                clipboardItems.removeAll(where: predicate)
            } else { clipboardItems.removeAll(where: predicate) }
            recordDeletion(removed)
            lastError = nil
            changed()
        } catch { setError(error) }
    }
    func undoDelete() {
        guard let removed = undoItems.last else { return }
        do {
            let current = settings.enableHistoryPersistence ? try store.readItems() : clipboardItems
            let existing = Set(current.map(\.id))
            let merged = current + removed.filter { !existing.contains($0.id) }
            if settings.enableHistoryPersistence {
                // Explicit undo may temporarily exceed capture retention until the next capture.
                try store.setItemLimit(0)
                clipboardItems = try store.replaceItems(merged)
            } else { clipboardItems = merged }
            undoItems.removeLast(); canUndo = !undoItems.isEmpty; lastError = nil; changed()
        } catch { setError(error) }
    }
    func getStorageInfo() -> ClipboardStore.StorageInfo {
        if settings.enableHistoryPersistence {
            let info = store.getStorageInfo()
            if let error = store.lastError { lastError = error }
            return info
        }
        let size = clipboardItems.reduce(Int64(0)) { $0 + Int64($1.residentPayloadBytes) }
        return .init(itemCount: clipboardItems.count, totalSize: size, cachePath: AppLanguage.text("仅内存", "Memory only"))
    }
    @discardableResult func maintainStorage(preserving items: [ClipboardItem] = []) -> ClipboardStore.MaintenanceResult? {
        guard settings.enableHistoryPersistence else { return nil }
        do {
            let result = try store.maintainAttachments(preserving: items + undoItems.flatMap { $0 })
            store.checkpointWhenIdle()
            return result
        } catch { setError(error); return nil }
    }
    var residentHistoryBytes: Int { clipboardItems.reduce(0) { $0 + $1.residentPayloadBytes } }
    var residentUndoBytes: Int { undoItems.flatMap { $0 }.reduce(0) { $0 + $1.residentPayloadBytes } }
    func performManualCleanup() {
        if settings.enableHistoryPersistence {
            store.performRetentionCleanup()
            let cleanupError = store.lastError
            reload()
            if let cleanupError { lastError = cleanupError }
        }
        else if settings.autoCleanupDays > 0 {
            let cutoff = Date().addingTimeInterval(-Double(settings.autoCleanupDays) * 86_400)
            clipboardItems.removeAll { !$0.isFavorite && !$0.isPinned && $0.timestamp < cutoff }
            changed()
        }
    }
    func searchItems(with query: String) -> [ClipboardItem] {
        let words = query.split(whereSeparator: \.isWhitespace).map(String.init)
        guard !words.isEmpty else { return clipboardItems }
        if settings.enableHistoryPersistence {
            do { return try store.searchItems(query) } catch { setError(error); return [] }
        }
        return clipboardItems.filter { item in
            let searchable = ([item.content, item.sourceApp ?? "", item.sourceAppName ?? ""] + item.tags).joined(separator: " ")
            return words.allSatisfy { searchable.localizedStandardContains($0) }
        }
    }
    private func updateFilteredItems() { filteredItems = searchItems(with: searchText) }
    private func limited(_ items: [ClipboardItem]) -> [ClipboardItem] {
        guard settings.maxItems > 0 else { return items }
        return items.filter { $0.isFavorite || $0.isPinned } + items.filter { !$0.isFavorite && !$0.isPinned }.sorted { $0.timestamp > $1.timestamp }.prefix(settings.maxItems)
    }
    private func memorySnapshot(_ item: ClipboardItem) throws -> ClipboardItem {
        guard !ClipboardAttachments.paths(in: item).isEmpty else { return item }
        // Retain copied files in RAM so disabling history persistence writes no history attachments.
        let archive = try HistoryArchive.make(items: [item])
        guard archive.files.reduce(0, { $0 + ($1.data?.count ?? 0) }) <= 64 * 1024 * 1024 else { throw ClipboardError.dataCorrupted }
        var result = item
        result.content = try item.fullContent()
        result.filePath = nil; result.fileURLs = nil; result.data = nil
        result.representations = [Self.memoryArchiveType: try JSONEncoder().encode(archive)]
        return result
    }
    func createItemHash(_ item: ClipboardItem) -> String {
        var hash = SHA256()
        func add(_ string: String) { hash.update(data: Data(string.utf8)); hash.update(data: Data([0])) }
        add(item.type.rawValue); add(item.contentDigest)
        if let bytes = item.data { add(ClipboardBlobReference.digest(bytes)) }
        else if item.type == .image, (item.fileURLs ?? []).isEmpty, let path = item.filePath,
                let bytes = try? Data(contentsOf: URL(fileURLWithPath: path), options: .mappedIfSafe) { add(ClipboardBlobReference.digest(bytes)) }
        if let paths = item.fileURLs { paths.forEach(add) }
        let formats = item.representationDigests
        for key in formats.keys.sorted() { add(key); add(formats[key]!) }
        return hash.finalize().map { String(format: "%02x", $0) }.joined()
    }
    deinit {
        timer?.invalidate()
        if let languageObserver { NotificationCenter.default.removeObserver(languageObserver) }
        for directory in temporaryPasteDirectories { try? FileManager.default.removeItem(at: directory) }
    }
}
