import AppKit
import SwiftUI

/// Uses the normal paste conversion without replacing the user's general clipboard.
/// Detached writers remain valid after the temporary pasteboard is released.
enum QuickPasteDragPayload {
    static func writers(for item: ClipboardItem, manager: ClipboardManager = .shared) throws -> [NSPasteboardWriting] {
        var sanitized = try item.materialized()
        let omittedTypes: Set<String> = [
            NSPasteboard.PasteboardType.fileURL.rawValue,
            "NSFilenamesPboardType", "com.apple.pasteboard.promised-file-url",
            "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType"
        ]
        // Retained file paths and RAM archives are authoritative. A captured file-URL
        // representation on a text/image record can point at an expired source file.
        sanitized.representations = sanitized.representations?.filter { type, bytes in
            guard !omittedTypes.contains(type) else { return false }
            if type == NSPasteboard.PasteboardType.URL.rawValue,
               let text = String(data: bytes, encoding: .utf8),
               URL(string: text)?.isFileURL == true { return false }
            return true
        }
        let staging = NSPasteboard(name: .init("CClip.QuickDrag.\(UUID().uuidString)"))
        defer { staging.releaseGlobally() }
        try manager.writeToClipboard(sanitized, board: staging)
        let writers: [NSPasteboardWriting] = try (staging.pasteboardItems ?? []).map { source in
            let writer = NSPasteboardItem()
            for type in source.types {
                guard let data = source.data(forType: type), writer.setData(data, forType: type) else {
                    throw ClipboardError.dataCorrupted
                }
            }
            if item.type == .image, writer.string(forType: .fileURL) == nil {
                try addImageFile(to: writer, manager: manager)
            }
            if item.type == .text, writer.string(forType: .URL) == nil,
               let text = writer.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
               !text.contains(where: { $0.isWhitespace }), let url = URLComponents(string: text),
               ["http", "https"].contains(url.scheme?.lowercased() ?? ""),
               let host = url.host, !host.isEmpty {
                guard writer.setString(text, forType: .URL) else { throw ClipboardError.dataCorrupted }
            }
            guard !writer.types.isEmpty else { throw ClipboardError.dataCorrupted }
            return writer
        }
        guard !writers.isEmpty else { throw ClipboardError.dataCorrupted }
        return writers
    }

    private static func addImageFile(to writer: NSPasteboardItem, manager: ClipboardManager) throws {
        // Image editors can read pixels; upload areas and file destinations often
        // require a real file. Offer both representations on one item, not two drops.
        let originalPNG = writer.data(forType: .png)
        guard let data = originalPNG ?? writer.data(forType: .tiff),
              let image = NSImage(data: data), let tiff = image.tiffRepresentation,
              let png = originalPNG ?? NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]) else {
            throw ClipboardError.imageProcessingFailed
        }
        let url = try manager.imageDragFile(for: png)
        guard writer.setData(png, forType: .png),
              writer.setData(tiff, forType: .tiff),
              writer.setString(url.absoluteString, forType: .fileURL) else {
            throw ClipboardError.dataCorrupted
        }
    }
}

struct QuickPasteDragView: NSViewRepresentable {
    @ObservedObject private var appLanguage = AppLanguage.shared
    var item: ClipboardItem
    var content: AnyView
    var isSelected: Bool
    var onSelect: () -> Void
    var onActivate: () -> Void
    var onDragBegan: () -> Void
    var onDragEnded: (DragCompletion) -> Void
    var onContextAction: (QuickPasteContextAction, UUID) -> Void = { _, _ in }
    var onContextMenuTrackingChanged: (Bool) -> Void = { _ in }
    var isInteractionEnabled = true

    func makeNSView(context: Context) -> QuickPasteDragHostingView {
        let view = QuickPasteDragHostingView(rootView: content)
        configure(view)
        return view
    }

    func updateNSView(_ view: QuickPasteDragHostingView, context: Context) {
        view.rootView = content
        configure(view)
    }

    private func configure(_ view: QuickPasteDragHostingView) {
        view.item = item
        view.onSelect = onSelect
        view.onActivate = onActivate
        view.onDragBegan = onDragBegan
        view.onDragEnded = onDragEnded
        view.onContextAction = onContextAction
        view.onContextMenuTrackingChanged = onContextMenuTrackingChanged
        view.isInteractionEnabled = isInteractionEnabled
        view.setAccessibilityElement(true)
        view.setAccessibilityRole(.button)
        view.setAccessibilityLabel(ClipboardSourceInfo.name(for: item) + " · " + quickPasteKind(item) + " · " + String(item.displayContent.prefix(160)))
        view.setAccessibilityValue(isSelected ? L("已选中", "Selected") : "")
        view.toolTip = L("拖拽中按右键取消。", "Right-click during a drag to cancel.")
        view.setAccessibilityHelp(L("单击选择，双击粘贴，拖动到目标应用；拖拽中按右键取消。平时右键可修改、收藏或删除。", "Click to select, double-click to paste, or drag to the destination app. Right-click during a drag to cancel; otherwise right-click to edit, favorite, or delete."))
    }
}

/// The card owns mouse tracking; hosted text and images cannot intercept its drag.
final class QuickPasteDragHostingView: NSHostingView<AnyView> {
    var item: ClipboardItem?
    var onSelect: () -> Void = {}
    var onActivate: () -> Void = {}
    var onDragBegan: () -> Void = {}
    var onDragEnded: (DragCompletion) -> Void = { _ in }
    var onContextAction: (QuickPasteContextAction, UUID) -> Void = { _, _ in }
    var onContextMenuTrackingChanged: (Bool) -> Void = { _ in }
    var isInteractionEnabled = true
    private var mouseDownLocation: NSPoint?
    private var attemptedDrag = false
    private var activeDrag = false
    private var dragEndHandler: ((DragCompletion) -> Void)?
    private var dragSource: QuickPasteDraggingSource?

    override func hitTest(_ point: NSPoint) -> NSView? {
        super.hitTest(point) == nil ? nil : self
    }

    override func mouseDown(with event: NSEvent) {
        guard isInteractionEnabled, !PrivacyLock.shared.locked, !activeDrag,
              DragCancellationController.shared.canBeginDrag else { return }
        if event.modifierFlags.contains(.control) { showContextMenu(with: event); return }
        mouseDownLocation = event.locationInWindow
        attemptedDrag = false
        onSelect()
    }

    override func rightMouseDown(with event: NSEvent) { showContextMenu(with: event) }

    func makeContextMenu() -> QuickPasteContextMenu? {
        guard isInteractionEnabled, !PrivacyLock.shared.locked, !activeDrag, let id = item?.id,
              let current = ClipboardManager.shared.clipboardItems.first(where: { $0.id == id }) else { return nil }
        return QuickPasteContextMenu(item: current, onAction: onContextAction)
    }

    private func showContextMenu(with event: NSEvent) {
        mouseDownLocation = nil
        attemptedDrag = false
        guard let menu = makeContextMenu() else { return }
        onSelect()
        onContextMenuTrackingChanged(true)
        defer { onContextMenuTrackingChanged(false) }
        NSMenu.popUpContextMenu(menu, with: event, for: self)
    }

    override func mouseUp(with event: NSEvent) {
        defer { mouseDownLocation = nil }
        guard isInteractionEnabled, mouseDownLocation != nil, !attemptedDrag, !activeDrag, !PrivacyLock.shared.locked else { return }
        if event.clickCount == 2 { onActivate() }
    }

    override func mouseDragged(with event: NSEvent) {
        guard isInteractionEnabled, !PrivacyLock.shared.locked, !attemptedDrag, !activeDrag,
              DragCancellationController.shared.canBeginDrag,
              let origin = mouseDownLocation, let item else { return }
        let delta = event.locationInWindow
        guard hypot(delta.x - origin.x, delta.y - origin.y) >= 5 else { return }
        attemptedDrag = true
        do {
            let writers = try QuickPasteDragPayload.writers(for: item)
            guard !PrivacyLock.shared.locked else { throw ClipboardError.accessDenied }
            guard let bitmap = bitmapImageRepForCachingDisplay(in: bounds) else { throw ClipboardError.imageProcessingFailed }
            cacheDisplay(in: bounds, to: bitmap)
            let preview = NSImage(size: bounds.size)
            preview.addRepresentation(bitmap)
            let draggingItems = writers.enumerated().map { index, writer in
                let draggingItem = NSDraggingItem(pasteboardWriter: writer)
                // A multi-file record has one visible card, but every URL is delivered.
                draggingItem.setDraggingFrame(bounds, contents: index == 0 ? preview : nil)
                return draggingItem
            }
            dragEndHandler = onDragEnded
            // NSHostingView already implements NSDraggingSource with non-open methods.
            // A retained delegate receives our native session lifecycle independently.
            // Retain the actual card host through the native session. A lock or
            // history update can remove it from SwiftUI even while its panel lives.
            // Ending the session clears dragSource and breaks this temporary cycle.
            let source = QuickPasteDraggingSource(onBegin: { [self] in
                self.activeDrag = true
                self.onDragBegan()
            }, onEnd: { [self] result in
                self.activeDrag = false
                self.mouseDownLocation = nil
                let completion = self.dragEndHandler
                self.dragEndHandler = nil
                self.dragSource = nil
                completion?(result)
            })
            dragSource = source
            let session = beginDraggingSession(with: draggingItems, event: event, source: source)
            session.animatesToStartingPositionsOnCancelOrFail = false
            session.draggingFormation = .none
            if let warning = ClipboardManager.shared.lastError { WorkflowState.shared.status = warning }
        } catch {
            let message = L("无法拖出内容：", "Unable to drag this item: ") + error.localizedDescription
            ClipboardManager.shared.lastError = message
            WorkflowState.shared.status = message
            NSSound.beep()
        }
    }

    override func accessibilityPerformPress() -> Bool {
        guard isInteractionEnabled, !PrivacyLock.shared.locked else { return false }
        onSelect()
        onActivate()
        return true
    }
}

private final class QuickPasteDraggingSource: NSObject, NSDraggingSource {
    private let onBegin: () -> Void
    private let onEnd: (DragCompletion) -> Void
    private var cancellationToken: UUID?
    private var ended = false

    init(onBegin: @escaping () -> Void, onEnd: @escaping (DragCompletion) -> Void) {
        self.onBegin = onBegin
        self.onEnd = onEnd
    }

    func draggingSession(_ session: NSDraggingSession, sourceOperationMaskFor context: NSDraggingContext) -> NSDragOperation {
        PrivacyLock.shared.locked || DragCancellationController.shared.isCancelled(cancellationToken) ? [] : .copy
    }

    func draggingSession(_ session: NSDraggingSession, willBeginAt screenPoint: NSPoint) {
        cancellationToken = DragCancellationController.shared.begin()
        session.animatesToStartingPositionsOnCancelOrFail = false
        onBegin()
    }

    func draggingSession(_ session: NSDraggingSession, endedAt screenPoint: NSPoint, operation: NSDragOperation) {
        guard !ended else { return }
        ended = true
        let cancelled = DragCancellationController.shared.end(cancellationToken)
        cancellationToken = nil
        onEnd(operation != [] ? .accepted : cancelled ? .cancelled : .notAccepted)
    }
}
